### ISSUE TITLE
未适配4.4的系统，添加AppCompatDelegate.setCompatVectorFromResourcesEnabled() 还是报错

### ISSUE THREAD

**Issue by zouyuanfeng** [xuexiangjys/XUI#1]
```
    android.content.res.Resources$NotFoundException: File res/drawable/md_btn_selector.xml from drawable resource ID #0x7f08008e. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
        at android.content.res.Resources.loadDrawable(Resources.java:2096)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
        at com.xuexiang.xui.utils.ThemeUtils.resolveDrawable(ThemeUtils.java:172)
        at com.xuexiang.xui.utils.ThemeUtils.resolveDrawable(ThemeUtils.java:163)
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog.getButtonSelector(MaterialDialog.java:382)
        at com.xuexiang.xui.widget.dialog.materialdialog.DialogInit.init(DialogInit.java:319)
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog.<init>(MaterialDialog.java:119)
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.build(MaterialDialog.java:2444)
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.show(MaterialDialog.java:2449)
        at com.itzyf.pokemondata.activity.PanelDetailActivity.showContractDialog(PanelDetailActivity.kt:130)
        at com.itzyf.pokemondata.activity.PanelDetailActivity.access$showContractDialog(PanelDetailActivity.kt:20)
        at com.itzyf.pokemondata.activity.PanelDetailActivity$handlerActivity$5.onClick(PanelDetailActivity.kt:76)
        at android.view.View.performClick(View.java:4438)
        at android.view.View$PerformClick.run(View.java:18422)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5050)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/md_btn_selected.xml from drawable resource ID #0x7f08008c
        at android.content.res.Resources.loadDrawable(Resources.java:2096)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:75)
        at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:432)
        at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:68)
        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:176)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2092)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
        at com.xuexiang.xui.utils.ThemeUtils.resolveDrawable(ThemeUtils.java:172) 
        at com.xuexiang.xui.utils.ThemeUtils.resolveDrawable(ThemeUtils.java:163) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog.getButtonSelector(MaterialDialog.java:382) 
        at com.xuexiang.xui.widget.dialog.materialdialog.DialogInit.init(DialogInit.java:319) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog.<init>(MaterialDialog.java:119) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.build(MaterialDialog.java:2444) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.show(MaterialDialog.java:2449) 
        at com.itzyf.pokemondata.activity.PanelDetailActivity.showContractDialog(PanelDetailActivity.kt:130) 
        at com.itzyf.pokemondata.activity.PanelDetailActivity.access$showContractDialog(PanelDetailActivity.kt:20) 
        at com.itzyf.pokemondata.activity.PanelDetailActivity$handlerActivity$5.onClick(PanelDetailActivity.kt:76) 
        at android.view.View.performClick(View.java:4438) 
        at android.view.View$PerformClick.run(View.java:18422) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5050) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x2
        at android.content.res.TypedArray.getDimensionPixelOffset(TypedArray.java:431)
        at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:1019)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
        at android.graphics.drawable.InsetDrawable.inflate(InsetDrawable.java:113)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2092)
        at android.content.res.Resources.getDrawable(Resources.java:700) 
        at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:75) 
        at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:432) 
        at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:68) 
        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:176) 
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937) 
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877) 
        at android.content.res.Resources.loadDrawable(Resources.java:2092) 
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
        at com.xuexiang.xui.utils.ThemeUtils.resolveDrawable(ThemeUtils.java:172) 
        at com.xuexiang.xui.utils.ThemeUtils.resolveDrawable(ThemeUtils.java:163) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog.getButtonSelector(MaterialDialog.java:382) 
        at com.xuexiang.xui.widget.dialog.materialdialog.DialogInit.init(DialogInit.java:319) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog.<init>(MaterialDialog.java:119) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.build(MaterialDialog.java:2444) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.show(MaterialDialog.java:2449) 
        at com.itzyf.pokemondata.activity.PanelDetailActivity.showContractDialog(PanelDetailActivity.kt:130) 
        at com.itzyf.pokemondata.activity.PanelDetailActivity.access$showContractDialog(PanelDetailActivity.kt:20) 
        at com.itzyf.pokemondata.activity.PanelDetailActivity$handlerActivity$5.onClick(PanelDetailActivity.kt:76) 
        at android.view.View.performClick(View.java:4438) 
        at android.view.View$PerformClick.run(View.java:18422) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5050) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by xuexiangjys** [comment]
感谢你的issue，由于一时疏忽，有个别的资源忘记做兼容了，目前已修复 @zouyuanfeng 
详细参见 bd4c02facd630d416642eaa37fb249ada59d246f
