### ISSUE TITLE
在最新版的AS中的设计器预览问题

### ISSUE THREAD

**Issue by yangxj96** [xuexiangjys/XUI#149]
`
java.lang.ExceptionInInitializerError: 请先在全局Application中调用 XUI.init() 初始化！
    at com.xuexiang.xui.XUI.testInitialize(XUI.java:73)
    at com.xuexiang.xui.XUI.getContext(XUI.java:67)
    at com.xuexiang.xui.utils.ResUtils.getResources(ResUtils.java:45)
    at com.xuexiang.xui.utils.DensityUtils.dp2px(DensityUtils.java:41)
    at com.xuexiang.xui.widget.actionbar.TitleBar.initAttrs(TitleBar.java:156)
    at com.xuexiang.xui.widget.actionbar.TitleBar.<init>(TitleBar.java:128)
    at com.xuexiang.xui.widget.actionbar.TitleBar.<init>(TitleBar.java:123)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:351)
    at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:200)
    at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:161)
    at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
    at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:359)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:436)
    at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
    at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
    at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
`

堆栈如上,
我已经自定义了Application,且在onCraete中添加了XUI.init(this) 和XUI.debug(true)
但是设计器的预览还是报错了. 我重新编译项目和清除所有缓存都尝试过,没效果

**Comment by k1366701532** [comment]
先使用 这个版本吧 ：https://dl.google.com/edgedl/android/studio/ide-zips/2021.3.1.5/android-studio-2021.3.1.5-windows.zip?rm=sn-ni5es7s&req_id=c87a6df786e34244

**Comment by k1366701532** [comment]
先使用 这个版本吧 ：https://dl.google.com/edgedl/android/studio/ide-zips/2021.3.1.5/android-studio-2021.3.1.5-windows.zip
