### ISSUE TITLE
showSimpleBottomSheetList 出错

### ISSUE THREAD

**Issue by mczha** [xuexiangjys/XUI#15]
android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class TextView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:19790)
        at com.xuexiang.xui.widget.dialog.bottomsheet.BottomSheet$BottomListSheetBuilder.buildViews(BottomSheet.java:348)
        at com.xuexiang.xui.widget.dialog.bottomsheet.BottomSheet$BottomListSheetBuilder.build(BottomSheet.java:338)
        at

**Comment by xuexiangjys** [comment]
1.请在使用前认真按照文档进行引用，你这个是没有设置[主题](https://github.com/xuexiangjys/XUI#%E8%B0%83%E6%95%B4%E5%BA%94%E7%94%A8%E7%9A%84%E5%9F%BA%E7%A1%80%E4%B8%BB%E9%A2%98)导致的。
2.其次你这个没有按模板来提交issue，一般我是不予理会的。

**Comment by mczha** [comment]
好的，明白了，已经设置主题了，出错的，下次会按照模板提交issue的
