### ISSUE TITLE
toast 

### ISSUE THREAD

**Issue by qs-lll** [xuexiangjys/XUI#173]

**Comment by qs-lll** [comment]
java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
2023-11-08 11:11:49.523 14295-14406 System.err              com.tuxi.cbox                        W  	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:157)
2023-11-08 11:11:49.524 14295-14406 System.err              com.tuxi.cbox                        W  	at android.widget.Toast.getLooper(Toast.java:179)
2023-11-08 11:11:49.524 14295-14406 System.err              com.tuxi.cbox                        W  	at android.widget.Toast.<init>(Toast.java:164)
2023-11-08 11:11:49.524 14295-14406 System.err              com.tuxi.cbox                        W  	at android.widget.Toast.makeText(Toast.java:492)
2023-11-08 11:11:49.524 14295-14406 System.err              com.tuxi.cbox                        W  	at android.widget.Toast.makeText(Toast.java:480)
2023-11-08 11:11:49.526 14295-14406 System.err              com.tuxi.cbox                        W  	at com.xuexiang.xui.widget.toast.XToast.custom(XToast.java:298)
2023-11-08 11:11:49.526 14295-14406 System.err              com.tuxi.cbox                        W  	at com.xuexiang.xui.widget.toast.XToast.error(XToast.java:240)
2023-11-08 11:11:49.526 14295-14406 System.err              com.tuxi.cbox                        W  	at com.xuexiang.xui.widget.toast.XToast.error(XToast.java:218)
