### ISSUE TITLE
xmd_layout_stub_title_frame: Error inflating class

### ISSUE THREAD

**Issue by cydenghua** [xuexiangjys/XUI#185]
在AppCompatActivity中：
        new MaterialDialog.Builder(getContext())
                .show();

报错：
2024-06-08 12:31:20.287 7122-7122/com.qm.qmsalecoin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qm.qmsalecoin, PID: 7122
    android.view.InflateException: Binary XML file line #26 in com.qm.qmsalecoin:layout/xmd_layout_dialog_basic: Binary XML file line #11 in com.qm.qmsalecoin:layout/xmd_layout_stub_title_frame: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #11 in com.qm.qmsalecoin:layout/xmd_layout_stub_title_frame: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createView(LayoutInflater.java:774)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1231)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog.<init>(MaterialDialog.java:123)
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.build(MaterialDialog.java:2465)
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.show(MaterialDialog.java:2470)
        at com.qm.qmsalecoin.activity.sale.SaleActivity.ccc(SaleActivity.java:59)
        at com.qm.qmsalecoin.activity.sale.SaleActivity_ViewBinding$1.doClick(SaleActivity_ViewBinding.java:36)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 16: TypedValue{t=0x2/d=0x7f0403f3 a=-1}
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:782)
        at android.view.View.<init>(View.java:5560)
        at android.view.ViewGroup.<init>(ViewGroup.java:697)
        at android.widget.LinearLayout.<init>(LinearLayout.java:254)
        at android.widget.LinearLayout.<init>(LinearLayout.java:250)
        at android.widget.LinearLayout.<init>(LinearLayout.java:246)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:852) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:774) 
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002) 
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1231) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog.<init>(MaterialDialog.java:123) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.build(MaterialDialog.java:2465) 
        at com.xuexiang.xui.widget.dialog.materialdialog.MaterialDialog$Builder.show(MaterialDialog.java:2470) 
        at com.qm.qmsalecoin.activity.sale.SaleActivity.ccc(SaleActivity.java:59) 
        at com.qm.qmsalecoin.activity.sale.SaleActivity_ViewBinding$1.doClick(SaleActivity_ViewBinding.java:36) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18) 
        at android.view.View.performClick(View.java:7448) 
        at android.view.View.performClickInternal(View.java:7425) 
        at android.view.View.access$3600(View.java:810) 
        at android.view.View$PerformClick.run(View.java:28305) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by houyuehai** [comment]
Binary XML file line #28 in com.hst.radarflow:layout/xui_dialog_loading: Binary XML file line #28 in com.hst.radarflow:layout/xui_dialog_loading: Error inflating class <unknown>
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #28 in com.hst.radarflow:layout/xui_dialog_loading: Error inflating class <unknown>
                                                                                                    同样的问题
